name: Build
run-name: ${{ github.actor }} ğŸš€
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ§ Compiling on a ${{ runner.os }} server in ${{ github.ref }}..."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in workspace
        run: |
          ls ${{ github.workspace }}
      - run: ls
      - run: cat Makefile
      - name: Build http server
        run: make http
      - run: echo "ğŸ This job's status is ${{ job.status }}."